[RayTracing]
r.RayTracing.EnableInGame=0
;[TestMap_Settings]
;+Settings="GraphicQuality=0,wp.Runtime.RuntimeGridLoadingRangeScale=0.2"
;+Settings=r.ViewDistanceScale=2.0
;+Settings=t.MaxFPS=50
[Internationalization]
PresetLanguage=En
PresetLanguage_Global=en
PresetLanguage_IWPlay=zh-Hant
PresetAudio=En
PresetAudio_Global=en
PresetAudio_IWPlay=ja
LanguageOptionEnable=false
[WaterMark]
WaterMarkEnable=false
