[ScalabilitySettings]
; Change engine defaults so a high end 2018 GPU will end up at a mix of Epic and High settings
; The resolution quality will need to be modified by users with 4k displays with the current autodetection system
PerfIndexThresholds_ResolutionQuality="GPU 250 370 550"
PerfIndexThresholds_ViewDistanceQuality="Min 120 250 370"
PerfIndexThresholds_AntiAliasingQuality="GPU 250 370 550"
PerfIndexThresholds_ShadowQuality="Min 120 250 370"
PerfIndexThresholds_GlobalIlluminationQuality="GPU 250 370 550"
PerfIndexThresholds_ReflectionQuality="GPU 250 370 550"
PerfIndexThresholds_PostProcessQuality="GPU 250 370 550"
PerfIndexThresholds_TextureQuality="GPU 250 370 550"
PerfIndexThresholds_EffectsQuality="Min 120 250 370"
PerfIndexThresholds_FoliageQuality="GPU 250 370 550"
PerfIndexThresholds_ShadingQuality="GPU 250 370 550"
;-----------------------------------------------------------------------------------------------------------------
; Change some shadow and reflection settings to match the map content
[ShadowQuality@0]
r.Shadow.DistanceScale=1
r.Shadow.PreshadowsForceLowestDetailLevel=1
r.Shadow.Virtual.ResolutionLodBiasDirectional=0
Slate.ForceBackgroundBlurLowQualityOverride=0
[ShadowQuality@1]
r.Shadow.DistanceScale=1.66
r.Shadow.PreshadowsForceLowestDetailLevel=1
r.Shadow.Virtual.ResolutionLodBiasDirectional=0
Slate.ForceBackgroundBlurLowQualityOverride=0
[ShadowQuality@2]
r.Shadow.DistanceScale=1.66
r.Shadow.PreshadowsForceLowestDetailLevel=1
r.Shadow.Virtual.ResolutionLodBiasDirectional=0
Slate.ForceBackgroundBlurLowQualityOverride=0
[ShadowQuality@3]
r.Shadow.DistanceScale=1
r.Shadow.PreshadowsForceLowestDetailLevel=0
r.Shadow.Virtual.ResolutionLodBiasDirectional=-1.5
Slate.ForceBackgroundBlurLowQualityOverride=0
[ShadowQuality@Cine]
r.Shadow.DistanceScale=1
r.Shadow.PreshadowsForceLowestDetailLevel=0
Slate.ForceBackgroundBlurLowQualityOverride=0
;-----------------------------------------------------------------------------------------------------------------
[ReflectionQuality@0]
r.Lumen.Reflections.Allow=0
r.Lumen.Reflections.DownsampleFactor=2
r.Lumen.Reflections.RadianceCache=1
[ReflectionQuality@1]
r.Lumen.Reflections.Allow=0
r.Lumen.Reflections.DownsampleFactor=2
r.Lumen.Reflections.RadianceCache=1
[ReflectionQuality@2]
r.Lumen.Reflections.Allow=1
r.Lumen.Reflections.DownsampleFactor=2
r.Lumen.Reflections.RadianceCache=1
[ReflectionQuality@3]
r.Lumen.Reflections.Allow=1
r.Lumen.Reflections.DownsampleFactor=2
r.Lumen.Reflections.RadianceCache=0
[ReflectionQuality@Cine]
r.Lumen.Reflections.Allow=1
r.Lumen.Reflections.DownsampleFactor=1
r.Lumen.Reflections.RadianceCache=0
;-----------------------------------------------------------------------------------------------------------------
[FoliageQuality@0]
foliage.DensityScale=0.2
grass.DensityScale=0.2
grass.CullDistanceScale=1.0
r.SubsurfaceEdgeBacklightEnhance=0
[FoliageQuality@1]
foliage.DensityScale=0.4
grass.DensityScale=0.4
grass.CullDistanceScale=1.0
r.SubsurfaceEdgeBacklightEnhance=1
[FoliageQuality@2]
foliage.DensityScale=0.8
grass.DensityScale=0.8
grass.CullDistanceScale=1.0
r.SubsurfaceEdgeBacklightEnhance=1
[FoliageQuality@3]
foliage.DensityScale=1.0
grass.DensityScale=1.0
grass.CullDistanceScale=1.0
r.SubsurfaceEdgeBacklightEnhance=1
[FoliageQuality@Cine]
foliage.DensityScale=1.0
grass.DensityScale=1.0
grass.CullDistanceScale=1.0
r.SubsurfaceEdgeBacklightEnhance=1
;-----------------------------------------------------------------------------------------------------------------
[ViewDistanceQuality@0]
wp.Runtime.GridLoadingRangeScale=0.6
wp.Runtime.GridLoadingRangeLevel=0
[ViewDistanceQuality@1]
wp.Runtime.GridLoadingRangeScale=0.78125
wp.Runtime.GridLoadingRangeLevel=1
[ViewDistanceQuality@2]
wp.Runtime.GridLoadingRangeScale=1.0
wp.Runtime.GridLoadingRangeLevel=2
[ViewDistanceQuality@3]
wp.Runtime.GridLoadingRangeScale=1.0
wp.Runtime.GridLoadingRangeLevel=3
[ViewDistanceQuality@Cine]
wp.Runtime.GridLoadingRangeScale=1.2
wp.Runtime.GridLoadingRangeLevel=3
;-----------------------------------------------------------------------------------------------------------------
[ShadingQuality@0]
r.AnisotropicMaterials=0
[ShadingQuality@1]
r.AnisotropicMaterials=0
[ShadingQuality@2]
r.AnisotropicMaterials=0
[ShadingQuality@3]
r.AnisotropicMaterials=0
[ShadingQuality@Cine]
r.AnisotropicMaterials=0
;-----------------------------------------------------------
[TextureQuality@0]
r.Streaming.Boost=1
r.Streaming.MipBias=0
r.Streaming.MaxNumTexturesToStreamPerFrame=0
[TextureQuality@1]
r.Streaming.Boost=1
r.Streaming.MipBias=0
r.Streaming.MaxNumTexturesToStreamPerFrame=0
[TextureQuality@2]
r.Streaming.Boost=1
r.Streaming.MipBias=0
r.Streaming.MaxNumTexturesToStreamPerFrame=0
[TextureQuality@3]
r.Streaming.Boost=1
r.Streaming.MipBias=0
r.Streaming.MaxNumTexturesToStreamPerFrame=0
[TextureQuality@Cine]
r.Streaming.Boost=1
r.Streaming.MipBias=0
r.Streaming.MaxNumTexturesToStreamPerFrame=0
;-----------------------------------------------------------------------------------------------------------------
[EffectsQuality@0]
r.TranslucencyLightingVolumeDim=16
HTAICharacter.IgnoreBornEffectDistThreshold=3000
[EffectsQuality@1]
r.TranslucencyLightingVolumeDim=16
HTAICharacter.IgnoreBornEffectDistThreshold=4000
[EffectsQuality@2]
r.TranslucencyLightingVolumeDim=16
HTAICharacter.IgnoreBornEffectDistThreshold=5000
[EffectsQuality@3]
r.TranslucencyLightingVolumeDim=16
HTAICharacter.IgnoreBornEffectDistThreshold=5500
[EffectsQuality@Cine]
r.TranslucencyLightingVolumeDim=16
HTAICharacter.IgnoreBornEffectDistThreshold=6500
;-----------------------------------------------------------
[GraphicsQuality@0]
sg.ViewDistanceQuality=0
sg.AntiAliasingQuality=0
sg.ShadowQuality=1
sg.GlobalIlluminationQuality=0
sg.ReflectionQuality=1
sg.PostProcessQuality=0
sg.TextureQuality=0
sg.EffectsQuality=0
sg.FoliageQuality=0
sg.ShadingQuality=0
a.Budget.BudgetMs=1.0
[GraphicsQuality@1]
sg.ViewDistanceQuality=1
sg.AntiAliasingQuality=1
sg.ShadowQuality=1
sg.GlobalIlluminationQuality=1
sg.ReflectionQuality=1
sg.PostProcessQuality=1
sg.TextureQuality=1
sg.EffectsQuality=1
sg.FoliageQuality=1
sg.ShadingQuality=1
a.Budget.BudgetMs=1.0
[GraphicsQuality@2]
sg.ViewDistanceQuality=2
sg.AntiAliasingQuality=2
sg.ShadowQuality=2
sg.GlobalIlluminationQuality=2
sg.ReflectionQuality=2
sg.PostProcessQuality=2
sg.TextureQuality=2
sg.EffectsQuality=2
sg.FoliageQuality=2
sg.ShadingQuality=2
a.Budget.BudgetMs=1.5
[GraphicsQuality@3]
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=3
sg.ShadowQuality=3
sg.GlobalIlluminationQuality=3
sg.ReflectionQuality=3
sg.PostProcessQuality=3
sg.TextureQuality=3
sg.EffectsQuality=3
sg.FoliageQuality=3
sg.ShadingQuality=3
a.Budget.BudgetMs=2.0
[GraphicsQuality@Cine]
sg.ViewDistanceQuality=4
sg.AntiAliasingQuality=4
sg.ShadowQuality=4
sg.GlobalIlluminationQuality=3
sg.ReflectionQuality=4
sg.PostProcessQuality=4
sg.TextureQuality=4
sg.EffectsQuality=4
sg.FoliageQuality=4
sg.ShadingQuality=4
a.Budget.BudgetMs=2.5
